apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: microservices
    tier: frontend

spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend

  template:
    metadata:
      labels:
        app: microservice
        tier: frontend

    spec:
      containers:
      - name: vue-app
        image: ghcr.io/wantotri/karsajobs/karsajobs-ui:latest
        ports:
          - containerPort: 8000

        env:
          # Set VUE_APP_BACKEND environment variable directly, ignoring .env file
          - name: VUE_APP_BACKEND
            # `localhost` is the ingress after running `minikube tunnel`
            value: "http://localhost/api"

        resources:
          requests:
            cpu: 20m
          limits:
            memory: 512Mi
            cpu: 500m