apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: microservices
    tier: frontend

spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: microservice
    tier: frontend
  type: NodePort