apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: microservices
    tier: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend

  template:
    metadata:
      labels:
        app: microservice
        tier: backend

    spec:
      containers:
      - name: server
        # Get image from GitHub Container Registry (ghcr)
        image: ghcr.io/wantotri/karsajobs/karsajobs:latest
        ports:
          - containerPort: 8080

        # Set environment variables for app port and mongodb connection
        env:
          - name: APP_PORT
            value: "8080"

          - name: MONGO_HOST
            value: "mongo"

          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_USERNAME

          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_PASSWORD

        resources:
          requests:
            cpu: 20m
          limits:
            memory: 128Mi
            cpu: 500m