apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: microservices
    tier: backend

spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend

  template:
    metadata:
      labels:
        app: microservice
        tier: backend

    spec:
      containers:
      - name: server
        image: ghcr.io/wantotri/karsajobs/karsajobs:latest
        ports:
          - containerPort: 8080

        env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: "$(MONGO_SERVICE_HOST)"
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: username
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: password

        resources:
          requests:
            cpu: 20m
          limits:
            memory: 128Mi
            cpu: 500m