apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo

spec:
  selector:
    matchLabels:
      app: mongo
      tier: backend

  serviceName: mongo
  replicas: 1
  minReadySeconds: 10

  template:
    metadata:
      labels:
        app: mongo
        tier: backend

    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo
        name: mongo

        env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   value: /etc/mongo-credentials/MONGO_ROOT_USERNAME

        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD

        - name: MONGO_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username

        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password

        ports:
        - containerPort: 27017
          name: mongo

        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db

      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim

